/**
 * Invoice Flow Service — Stripe Invoice First (parallel to legacy)
 *
 * Creates Stripe invoices BEFORE payment is collected, in two variants:
 *
 *   1. createForCorporate(bookingId)
 *      collection_method='send_invoice' + Stripe-emailed Hosted Invoice Page.
 *      Booking confirmed only when invoice.paid webhook fires.
 *
 *   2. createForInstant(bookingId)
 *      collection_method='charge_automatically' + Payment Element on the
 *      invoice's confirmation_secret.client_secret. Returned to the frontend
 *      so it can confirm the invoice's PaymentIntent in-page.
 *      Booking confirmed only when invoice.paid webhook fires.
 *
 * INTERDICTIONS (true invoice-first; Stripe-blessed pattern):
 *   - MUST NOT call stripe.paymentIntents.create
 *   - MUST NOT call stripe.invoices.attachPayment
 *   - MUST NOT call stripe.invoices.pay (especially with paid_out_of_band:true)
 *   - MUST NOT interact with StripeInvoiceService (legacy retroactive flow)
 *
 * SAFETY CONTRACT (addresses prior review feedback):
 *   1. Stripe idempotency keys are set on EVERY POST: invoices.create,
 *      invoiceItems.create, finalizeInvoice, sendInvoice, customers.create.
 *      Keys are deterministic on (booking_id, attempt_no, step). Retries from
 *      proxies / double-clicks / parallel requests cannot duplicate Stripe state.
 *
 *   2. Local row is persisted IMMEDIATELY after the draft is created
 *      (status='draft', stripe_invoice_id set), then UPDATED in place at each
 *      subsequent step. If a Stripe call after create fails and DB upsert is
 *      retried, the same booking_id+attempt yields the same idempotency key
 *      and Stripe returns the same invoice — no orphan invoices.
 *
 *   3. Reuse policy on existing invoice rows is explicit:
 *        paid           → return alreadyPaid=true, no new Stripe call
 *        open           → reuse, return same hosted_invoice_url / client_secret
 *        draft          → finalize that draft, then reuse
 *        void / uncollectible → create a NEW invoice (incremented attempt_no)
 *
 *   4. Stripe timestamps (status_transitions.finalized_at / paid_at) are
 *      preferred over local now() when present.
 *
 *   5. Stripe Customer is resolved through a local cache
 *      (customers.stripe_customer_id), then through email lookup, then
 *      created with an idempotency key keyed on (booking_id, customer_id).
 *
 * The PaymentIntent is generated by Stripe internally at finalizeInvoice.
 * Booking confirmation flows exclusively through invoice.* webhooks
 * (handled by InvoiceFirstWebhookService — separate service, separate dedup table).
 */

import Stripe from 'stripe';
import { supabase } from '../config/supabase';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2026-02-25.clover',
});

const CORPORATE_DAYS_UNTIL_DUE = Number(process.env.STRIPE_INVOICE_DAYS_UNTIL_DUE ?? 7);

export interface CorporateInvoiceResult {
  success: boolean;
  invoiceId?: string;
  invoiceNumber?: string;
  hostedInvoiceUrl?: string;
  alreadyExists?: boolean;
  alreadyPaid?: boolean;
  error?: string;
}

export interface InstantInvoiceResult {
  success: boolean;
  invoiceId?: string;
  invoiceNumber?: string;
  hostedInvoiceUrl?: string;
  clientSecret?: string;
  alreadyExists?: boolean;
  alreadyPaid?: boolean;
  error?: string;
}

interface ResolvedBooking {
  bookingId: string;
  reference: string;
  organizationId: string;
  customerId: string;
  amountPence: number;
  currency: string;          // lowercase (Stripe convention)
  dbCurrency: string;        // uppercase (DB convention)
  receiptEmail: string | null;
  /** One or more line items to create on the Stripe invoice.
   *  Sum of amount_pence == amountPence (guaranteed by builder).
   *  Falls back to a single item with amountPence when quote data is missing. */
  invoiceItems: InvoiceLineItem[];
}

interface InvoiceLineItem {
  description: string;
  amount_pence: number;
}

type InvoiceFlow = 'invoice_first_send' | 'invoice_first_charge';

interface ExistingInvoiceRow {
  id: string;
  attempt_no: number;
  stripe_invoice_id: string;
  stripe_invoice_number: string | null;
  hosted_invoice_url: string | null;
  status: string;
  stripe_invoice_status: string | null;
}

export class InvoiceFlowService {

  // --------------------------------------------------------------------------
  // Public API
  // --------------------------------------------------------------------------

  /**
   * Create a corporate-style invoice (collection_method='send_invoice') and
   * trigger Stripe to email the Hosted Invoice Page to the customer.
   * Idempotent end-to-end (Stripe idempotency keys + local row persisted early).
   */
  static async createForCorporate(bookingId: string): Promise<CorporateInvoiceResult> {
    const tag = '[InvoiceFlow][corporate]';
    try {
      console.log(`${tag} Starting for booking ${bookingId}`);

      // ---- Reuse policy on existing invoice (if any) -----------------------
      const reuse = await this.tryReuseExistingInvoice(bookingId, 'send_invoice', tag);
      if (reuse.handled) {
        return {
          success: true,
          invoiceId: reuse.invoiceId,
          invoiceNumber: reuse.invoiceNumber,
          hostedInvoiceUrl: reuse.hostedInvoiceUrl,
          alreadyExists: !reuse.alreadyPaid,
          alreadyPaid: reuse.alreadyPaid,
        };
      }

      const attemptNo = reuse.nextAttemptNo;
      const booking = await this.resolveBookingForInvoice(bookingId);
      const customerId = await this.resolveStripeCustomer(booking, tag, attemptNo);

      // ---- 1) Create draft (idempotent) ------------------------------------
      const draft = await stripe.invoices.create({
        customer: customerId,
        collection_method: 'send_invoice',
        days_until_due: CORPORATE_DAYS_UNTIL_DUE,
        auto_advance: false,
        currency: booking.currency,
        description: `Vantage Lane — Booking ${booking.reference}`,
        metadata: {
          booking_id: bookingId,
          booking_reference: booking.reference,
          flow: 'invoice_first_send',
          attempt_no: String(attemptNo),
        },
      }, {
        idempotencyKey: this.idempotencyKey(bookingId, attemptNo, 'invoice_create_send'),
      });
      console.log(`${tag} Draft invoice ${draft.id} customer=${customerId} amount=${booking.amountPence} attempt=${attemptNo}`);

      // ---- 2) Persist local row IMMEDIATELY (status='draft') ---------------
      // If subsequent Stripe steps fail and the request is retried, the
      // idempotency keys above will return the SAME draft, which we then
      // re-pick up via the existing-row reuse path on the next call.
      await this.upsertInvoicePaymentRow({
        bookingId,
        attemptNo,
        organizationId: booking.organizationId,
        customerId,
        amountPence: booking.amountPence,
        dbCurrency: booking.dbCurrency,
        receiptEmail: booking.receiptEmail,
        invoice: draft,
        rowStatus: 'unpaid',
        sent: false,
        flow: 'invoice_first_send',
      });

      // ---- 3) Add line items (idempotent, one per invoice item) ---------------
      for (let i = 0; i < booking.invoiceItems.length; i++) {
        const item = booking.invoiceItems[i]!;
        await stripe.invoiceItems.create({
          customer: customerId,
          invoice: draft.id,
          description: item.description,
          amount: item.amount_pence,
          currency: booking.currency,
        }, {
          idempotencyKey: this.idempotencyKey(bookingId, attemptNo, `invoice_item_send_${i}`),
        });
      }

      // ---- 4) Finalize (idempotent) ----------------------------------------
      const finalized = await stripe.invoices.finalizeInvoice(draft.id, undefined, {
        idempotencyKey: this.idempotencyKey(bookingId, attemptNo, 'invoice_finalize_send'),
      });
      console.log(`${tag} Finalized ${finalized.id} hosted=${finalized.hosted_invoice_url} number=${finalized.number}`);

      await this.updateInvoicePaymentRow({
        bookingId,
        attemptNo,
        invoice: finalized,
        sent: false,
        rowStatus: 'pending',
      });

      // ---- 5) Send (idempotent) → Stripe queues the email ------------------
      const sent = await stripe.invoices.sendInvoice(finalized.id, {
        idempotencyKey: this.idempotencyKey(bookingId, attemptNo, 'invoice_send_send'),
      });
      console.log(`${tag} Sent invoice ${sent.id} (Stripe email queued)`);

      await this.updateInvoicePaymentRow({
        bookingId,
        attemptNo,
        invoice: sent,
        sent: true,
        rowStatus: 'pending',
      });

      // ---- 6) Stamp booking flow + status ----------------------------------
      await this.stampBookingFlowAndStatus(bookingId, 'invoice_first_send', 'AWAITING_INVOICE_PAYMENT');

      return {
        success: true,
        invoiceId: sent.id,
        invoiceNumber: sent.number ?? undefined,
        hostedInvoiceUrl: sent.hosted_invoice_url ?? undefined,
      };
    } catch (error: any) {
      console.error(`${tag} Failed:`, error?.message ?? error);
      return { success: false, error: error?.message ?? 'Unknown error' };
    }
  }

  /**
   * Create an instant-style invoice (collection_method='charge_automatically'),
   * finalize it with `expand: ['confirmation_secret']`, and return the
   * client_secret so the frontend can confirm via Stripe Payment Element.
   *
   * Stripe-blessed pattern documented at:
   *   https://docs.stripe.com/invoicing/integration?element=payment&method=elements
   */
  static async createForInstant(bookingId: string): Promise<InstantInvoiceResult> {
    const tag = '[InvoiceFlow][instant]';
    try {
      console.log(`${tag} Starting for booking ${bookingId}`);

      // ---- Reuse policy on existing invoice (if any) -----------------------
      const reuse = await this.tryReuseExistingInvoice(bookingId, 'charge_automatically', tag);
      if (reuse.handled) {
        return {
          success: true,
          invoiceId: reuse.invoiceId,
          invoiceNumber: reuse.invoiceNumber,
          hostedInvoiceUrl: reuse.hostedInvoiceUrl,
          clientSecret: reuse.clientSecret,
          alreadyExists: !reuse.alreadyPaid,
          alreadyPaid: reuse.alreadyPaid,
        };
      }

      const attemptNo = reuse.nextAttemptNo;
      const booking = await this.resolveBookingForInvoice(bookingId);
      const customerId = await this.resolveStripeCustomer(booking, tag, attemptNo);

      // ---- 1) Create draft (idempotent) ------------------------------------
      const draft = await stripe.invoices.create({
        customer: customerId,
        collection_method: 'charge_automatically',
        auto_advance: false,
        currency: booking.currency,
        description: `Vantage Lane — Booking ${booking.reference}`,
        payment_settings: {
          payment_method_types: ['card', 'link'],
        },
        metadata: {
          booking_id: bookingId,
          booking_reference: booking.reference,
          flow: 'invoice_first_charge',
          attempt_no: String(attemptNo),
        },
      }, {
        idempotencyKey: this.idempotencyKey(bookingId, attemptNo, 'invoice_create_charge'),
      });
      console.log(`${tag} Draft ${draft.id} customer=${customerId} amount=${booking.amountPence} attempt=${attemptNo}`);

      // ---- 2) Persist local row IMMEDIATELY --------------------------------
      await this.upsertInvoicePaymentRow({
        bookingId,
        attemptNo,
        organizationId: booking.organizationId,
        customerId,
        amountPence: booking.amountPence,
        dbCurrency: booking.dbCurrency,
        receiptEmail: booking.receiptEmail,
        invoice: draft,
        rowStatus: 'unpaid',
        sent: false,
        flow: 'invoice_first_charge',
      });

      // ---- 3) Add line items (idempotent, one per invoice item) ---------------
      for (let i = 0; i < booking.invoiceItems.length; i++) {
        const item = booking.invoiceItems[i]!;
        await stripe.invoiceItems.create({
          customer: customerId,
          invoice: draft.id,
          description: item.description,
          amount: item.amount_pence,
          currency: booking.currency,
        }, {
          idempotencyKey: this.idempotencyKey(bookingId, attemptNo, `invoice_item_charge_${i}`),
        });
      }

      // ---- 4) Finalize with expanded confirmation_secret -------------------
      const finalized = await stripe.invoices.finalizeInvoice(draft.id, {
        expand: ['confirmation_secret'],
      }, {
        idempotencyKey: this.idempotencyKey(bookingId, attemptNo, 'invoice_finalize_charge'),
      });
      const clientSecret = (finalized as unknown as { confirmation_secret?: { client_secret?: string } })
        .confirmation_secret?.client_secret;
      if (!clientSecret) {
        throw new Error('Stripe did not return confirmation_secret on finalized invoice');
      }
      console.log(`${tag} Finalized ${finalized.id} → client_secret length=${clientSecret.length}`);

      await this.updateInvoicePaymentRow({
        bookingId,
        attemptNo,
        invoice: finalized,
        sent: false,
        rowStatus: 'pending',
      });

      // ---- 5) Stamp booking flow + status ----------------------------------
      await this.stampBookingFlowAndStatus(bookingId, 'invoice_first_charge', 'AWAITING_INVOICE_CONFIRM');

      return {
        success: true,
        invoiceId: finalized.id,
        invoiceNumber: finalized.number ?? undefined,
        hostedInvoiceUrl: finalized.hosted_invoice_url ?? undefined,
        clientSecret,
      };
    } catch (error: any) {
      console.error(`${tag} Failed:`, error?.message ?? error);
      return { success: false, error: error?.message ?? 'Unknown error' };
    }
  }

  // --------------------------------------------------------------------------
  // Reuse policy
  // --------------------------------------------------------------------------

  /**
   * Apply the explicit reuse policy:
   *   paid           → handled=true, alreadyPaid=true
   *   open           → handled=true (reuse)
   *   draft          → finalize that draft, then handled=true
   *   void / uncollectible → handled=false, nextAttemptNo incremented
   *   none           → handled=false, nextAttemptNo=1
   */
  private static async tryReuseExistingInvoice(
    bookingId: string,
    collectionMethod: 'send_invoice' | 'charge_automatically',
    tag: string,
  ): Promise<{
    handled: boolean;
    nextAttemptNo: number;
    invoiceId?: string;
    invoiceNumber?: string;
    hostedInvoiceUrl?: string;
    clientSecret?: string;
    alreadyPaid?: boolean;
  }> {
    const existing = await this.findLatestInvoiceRow(bookingId);
    if (!existing?.stripe_invoice_id) {
      return { handled: false, nextAttemptNo: 1 };
    }

    // Always re-fetch from Stripe — local row may be stale.
    const expand = collectionMethod === 'charge_automatically' ? ['confirmation_secret'] : undefined;
    let invoice: Stripe.Invoice;
    try {
      invoice = await stripe.invoices.retrieve(existing.stripe_invoice_id, { expand });
    } catch (err: any) {
      console.warn(`${tag} retrieve(${existing.stripe_invoice_id}) failed: ${err?.message}; will create new`);
      return { handled: false, nextAttemptNo: existing.attempt_no + 1 };
    }

    const status = invoice.status; // 'draft' | 'open' | 'paid' | 'void' | 'uncollectible'

    if (status === 'paid') {
      console.log(`${tag} Existing invoice ${invoice.id} already PAID — short-circuit`);
      // Make sure local row is up to date
      await this.updateInvoicePaymentRow({
        bookingId,
        attemptNo: existing.attempt_no,
        invoice,
        sent: collectionMethod === 'send_invoice',
        rowStatus: 'succeeded',
      });
      return {
        handled: true,
        nextAttemptNo: existing.attempt_no,
        invoiceId: invoice.id,
        invoiceNumber: invoice.number ?? undefined,
        hostedInvoiceUrl: invoice.hosted_invoice_url ?? undefined,
        alreadyPaid: true,
      };
    }

    if (status === 'open') {
      console.log(`${tag} Reusing OPEN invoice ${invoice.id}`);
      const cs = (invoice as unknown as { confirmation_secret?: { client_secret?: string } })
        .confirmation_secret?.client_secret;
      return {
        handled: true,
        nextAttemptNo: existing.attempt_no,
        invoiceId: invoice.id,
        invoiceNumber: invoice.number ?? undefined,
        hostedInvoiceUrl: invoice.hosted_invoice_url ?? undefined,
        clientSecret: cs,
      };
    }

    if (status === 'draft') {
      console.log(`${tag} Existing invoice ${invoice.id} is DRAFT — finalizing and reusing`);
      const finalized = await stripe.invoices.finalizeInvoice(invoice.id, { expand }, {
        idempotencyKey: this.idempotencyKey(
          bookingId,
          existing.attempt_no,
          collectionMethod === 'send_invoice' ? 'invoice_finalize_send' : 'invoice_finalize_charge',
        ),
      });
      let sent = false;
      if (collectionMethod === 'send_invoice') {
        await stripe.invoices.sendInvoice(finalized.id, {
          idempotencyKey: this.idempotencyKey(bookingId, existing.attempt_no, 'invoice_send_send'),
        });
        sent = true;
      }
      await this.updateInvoicePaymentRow({
        bookingId,
        attemptNo: existing.attempt_no,
        invoice: finalized,
        sent,
        rowStatus: 'pending',
      });
      const cs = (finalized as unknown as { confirmation_secret?: { client_secret?: string } })
        .confirmation_secret?.client_secret;
      return {
        handled: true,
        nextAttemptNo: existing.attempt_no,
        invoiceId: finalized.id,
        invoiceNumber: finalized.number ?? undefined,
        hostedInvoiceUrl: finalized.hosted_invoice_url ?? undefined,
        clientSecret: cs,
      };
    }

    // void / uncollectible → controlled retry with new attempt
    console.log(`${tag} Existing invoice ${invoice.id} status=${status} — creating new attempt`);
    return { handled: false, nextAttemptNo: existing.attempt_no + 1 };
  }

  // --------------------------------------------------------------------------
  // Invoice line item builder
  // --------------------------------------------------------------------------

  /**
   * Build the list of individual line items for a Stripe invoice.
   *
   * Strategy (in priority order):
   *   1. If extras IDs are known (from line_items.meta.trip.extras) and
   *      vehicle_subtotal_pence is available:
   *      - Fetch each extra's name + price from service_items table.
   *      - Show each paid extra as its own line.
   *      - Transport = totalPence − sum(extras) so the total always matches.
   *   2. If only the vehicle/services split is available (no extras IDs):
   *      - Show "Chauffeur service" and "Premium services" proportionally.
   *   3. Fallback: single line item with the full total.
   *
   * The sum of all returned amount_pence values is always == totalPence.
   */
  private static async buildInvoiceLineItems(
    reference: string,
    totalPence: number,
    vehicleSubtotalPence: number | null,
    servicesSubtotalPence: number | null,
    extrasIds: string[] | null,
  ): Promise<InvoiceLineItem[]> {
    const tag = '[InvoiceFlow][lineItems]';

    // ── Strategy 1: known extras IDs ──────────────────────────────────────
    if (
      extrasIds && extrasIds.length > 0 &&
      vehicleSubtotalPence !== null && vehicleSubtotalPence > 0
    ) {
      try {
        const extras = await this.resolveExtrasFromServiceItems(extrasIds);

        if (extras.length > 0) {
          const extrasTotalPence = extras.reduce((s, e) => s + e.amount_pence, 0);
          // Transport absorbs VAT, discount, rounding — always > 0 for real bookings.
          const transportPence = totalPence - extrasTotalPence;

          if (transportPence > 0) {
            return [
              { description: `Chauffeur service — Booking ${reference}`, amount_pence: transportPence },
              ...extras,
            ];
          }
          // Safety: if extras somehow exceed total, fall through to strategy 2.
          console.warn(`${tag} extras sum (${extrasTotalPence}p) >= total (${totalPence}p) — falling back`);
        }
      } catch (err) {
        console.warn(`${tag} service_items lookup failed:`, err);
        // Non-fatal — fall through to strategy 2/3.
      }
    }

    // ── Strategy 2: vehicle / services split (no individual extras names) ─
    if (
      vehicleSubtotalPence !== null && vehicleSubtotalPence > 0 &&
      servicesSubtotalPence !== null && servicesSubtotalPence > 0
    ) {
      const subtotal = vehicleSubtotalPence + servicesSubtotalPence;
      // Distribute totalPence proportionally; last item gets the remainder.
      const transportPence = Math.round(vehicleSubtotalPence / subtotal * totalPence);
      const servicesPence = totalPence - transportPence;
      return [
        { description: `Chauffeur service — Booking ${reference}`, amount_pence: transportPence },
        { description: `Premium services — Booking ${reference}`, amount_pence: servicesPence },
      ];
    }

    // ── Strategy 3: fallback — single item ───────────────────────────────
    return [
      { description: `Chauffeur Service — Booking ${reference}`, amount_pence: totalPence },
    ];
  }

  /**
   * Resolve display names + prices for a list of service item IDs.
   * Returns only the items that were actually found in the service_items table.
   */
  private static async resolveExtrasFromServiceItems(
    ids: string[],
  ): Promise<InvoiceLineItem[]> {
    if (!ids.length) return [];

    const { data, error } = await supabase
      .from('service_items')
      .select('id, name, price_pence')
      .in('id', ids)
      .eq('is_active', true);

    if (error || !data) return [];

    return data.map(item => ({
      description: item.name ?? item.id,
      amount_pence: Math.round(item.price_pence ?? 0),
    })).filter(i => i.amount_pence > 0);
  }

  // --------------------------------------------------------------------------
  // Helpers
  // --------------------------------------------------------------------------

  /**
   * Deterministic Stripe idempotency key. Same (booking_id, attempt_no, step)
   * → same key → Stripe returns the SAME object on retry instead of creating
   * a new one. Safe across proxy retries, double-clicks, and parallel requests.
   *
   * Stripe limits keys to 255 chars; ours are well under that.
   */
  private static idempotencyKey(bookingId: string, attemptNo: number, step: string): string {
    return `vlif:${bookingId}:${attemptNo}:${step}`;
  }

  private static async resolveBookingForInvoice(bookingId: string): Promise<ResolvedBooking> {
    const { data: booking, error } = await supabase
      .from('bookings')
      .select('id, customer_id, organization_id, currency, reference')
      .eq('id', bookingId)
      .single();

    if (error || !booking) {
      throw new Error(`Booking ${bookingId} not found`);
    }

    // Resolve amount: prefer client_booking_quotes (canonical), fallback to
    // latest booking_payment (covers retry of legacy → invoice migration cases).
    let amountPence = 0;
    const { data: quote } = await supabase
      .from('client_booking_quotes')
      .select('total_pence, vehicle_subtotal_pence, services_subtotal_pence, line_items')
      .eq('booking_id', bookingId)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle();
    amountPence = quote?.total_pence ?? 0;

    if (amountPence <= 0) {
      const { data: latestPayment } = await supabase
        .from('booking_payments')
        .select('amount_pence')
        .eq('booking_id', bookingId)
        .order('attempt_no', { ascending: false })
        .limit(1)
        .maybeSingle();
      amountPence = latestPayment?.amount_pence ?? 0;
    }

    if (!Number.isInteger(amountPence) || amountPence <= 0) {
      throw new Error(`Booking ${bookingId} has no resolvable amount (no quote, no payment)`);
    }

    // Always round to an integer number of pence before sending to Stripe.
    // Stripe requires integer amounts; a floating-point pence value (e.g. 9283.4)
    // would be silently truncated by some SDK versions or cause API errors.
    amountPence = Math.round(amountPence);

    // Build individual invoice line items from quote data (Etapa 1).
    const invoiceItems = await this.buildInvoiceLineItems(
      booking.reference ?? bookingId.slice(0, 8).toUpperCase(),
      amountPence,
      quote?.vehicle_subtotal_pence ?? null,
      quote?.services_subtotal_pence ?? null,
      (quote?.line_items as any)?.meta?.trip?.extras ?? null,
    );

    const { data: customer } = await supabase
      .from('customers')
      .select('id, email')
      .eq('id', booking.customer_id)
      .maybeSingle();

    const receiptEmail = customer?.email ?? null;

    const dbCurrency = (booking.currency || 'GBP').toUpperCase();
    if (!/^[A-Z]{3}$/.test(dbCurrency)) {
      throw new Error(`Invalid booking currency: ${dbCurrency}`);
    }

    return {
      bookingId: booking.id,
      reference: booking.reference ?? bookingId.slice(0, 8).toUpperCase(),
      organizationId: booking.organization_id,
      customerId: booking.customer_id,
      amountPence,
      currency: dbCurrency.toLowerCase(),
      dbCurrency,
      receiptEmail,
      invoiceItems,
    };
  }

  /**
   * Resolve a Stripe Customer with this priority:
   *   1. Local cache (customers.stripe_customer_id) — strongest, race-free.
   *   2. Stripe email lookup — fallback, may match legacy customers.
   *   3. Create new — keyed by idempotency key on (booking_id, attempt_no).
   *
   * The local cache is updated whenever (1) is empty and (2) or (3) succeeds.
   */
  private static async resolveStripeCustomer(
    booking: ResolvedBooking,
    tag: string,
    attemptNo: number,
  ): Promise<string> {
    // (1) Local cache
    const { data: cached } = await supabase
      .from('customers')
      .select('stripe_customer_id')
      .eq('id', booking.customerId)
      .maybeSingle();

    if (cached?.stripe_customer_id) {
      console.log(`${tag} Using cached Stripe customer ${cached.stripe_customer_id}`);
      return cached.stripe_customer_id;
    }

    if (!booking.receiptEmail) {
      throw new Error('Cannot create invoice: customer has no email on file');
    }

    // (2) Email lookup
    const existingList = await stripe.customers.list({
      email: booking.receiptEmail,
      limit: 1,
    });

    let stripeCustomerId: string;
    if (existingList.data.length > 0) {
      stripeCustomerId = existingList.data[0].id;
      console.log(`${tag} Found Stripe customer by email ${stripeCustomerId} for ${booking.receiptEmail}`);
    } else {
      // (3) Create with idempotency key
      const created = await stripe.customers.create({
        email: booking.receiptEmail,
        metadata: {
          booking_id: booking.bookingId,
          customer_id: booking.customerId,
        },
      }, {
        idempotencyKey: this.idempotencyKey(booking.bookingId, attemptNo, 'customer_create'),
      });
      stripeCustomerId = created.id;
      console.log(`${tag} Created Stripe customer ${stripeCustomerId} for ${booking.receiptEmail}`);
    }

    // Cache locally for next time (best-effort; failure here is non-fatal).
    const { error: cacheErr } = await supabase
      .from('customers')
      .update({ stripe_customer_id: stripeCustomerId, updated_at: new Date().toISOString() })
      .eq('id', booking.customerId)
      .is('stripe_customer_id', null);
    if (cacheErr) {
      console.warn(`${tag} Failed to cache stripe_customer_id locally: ${cacheErr.message}`);
    }

    return stripeCustomerId;
  }

  /**
   * Persist a NEW booking_payments row for this attempt with the given
   * draft/finalized invoice. Uses (idempotency_key) for upsert idempotency.
   * Local row carries the full invoice context from creation onward, so a
   * later step crashing cannot lose the link to the Stripe invoice.
   */
  private static async upsertInvoicePaymentRow(args: {
    bookingId: string;
    attemptNo: number;
    organizationId: string;
    customerId: string;
    amountPence: number;
    dbCurrency: string;
    receiptEmail: string | null;
    invoice: Stripe.Invoice;
    rowStatus: 'unpaid' | 'pending' | 'succeeded';
    sent: boolean;
    flow: InvoiceFlow;
  }): Promise<void> {
    const idempotencyKey = `inv_${args.bookingId}_${args.attemptNo}_${args.invoice.id}`;
    const finalizedAt = this.stripeFinalizedAt(args.invoice);
    const sentAt = args.sent ? this.nowIso() : null;

    const row = {
      booking_id: args.bookingId,
      organization_id: args.organizationId,
      stripe_customer_id: args.customerId,
      amount_pence: args.amountPence,
      currency: args.dbCurrency,
      status: args.rowStatus,
      receipt_email: args.receiptEmail,
      idempotency_key: idempotencyKey,
      attempt_no: args.attemptNo,
      livemode: args.invoice.livemode,
      payment_kind: 'full',
      stripe_invoice_id: args.invoice.id,
      stripe_invoice_status: args.invoice.status ?? 'draft',
      stripe_invoice_number: args.invoice.number ?? null,
      hosted_invoice_url: args.invoice.hosted_invoice_url ?? null,
      invoice_finalized_at: finalizedAt,
      invoice_sent_at: sentAt,
      metadata: {
        flow: args.flow,
        invoice_id: args.invoice.id,
        invoice_number: args.invoice.number,
      },
      updated_at: this.nowIso(),
    };

    const { error } = await supabase
      .from('booking_payments')
      .upsert(row, { onConflict: 'idempotency_key' });

    if (error) {
      throw new Error(`Failed to persist booking_payment row: ${error.message}`);
    }
  }

  /**
   * UPDATE an existing row (matched by booking_id + attempt_no + invoice_id)
   * with the latest invoice snapshot. Used after finalize and after send.
   */
  private static async updateInvoicePaymentRow(args: {
    bookingId: string;
    attemptNo: number;
    invoice: Stripe.Invoice;
    sent: boolean;
    rowStatus: 'pending' | 'succeeded';
  }): Promise<void> {
    const finalizedAt = this.stripeFinalizedAt(args.invoice);
    const paidAt = this.stripePaidAt(args.invoice);
    const sentAt = args.sent ? this.nowIso() : null;

    const update: Record<string, unknown> = {
      stripe_invoice_status: args.invoice.status ?? null,
      stripe_invoice_number: args.invoice.number ?? null,
      hosted_invoice_url: args.invoice.hosted_invoice_url ?? null,
      status: args.rowStatus,
      updated_at: this.nowIso(),
    };
    if (finalizedAt) update.invoice_finalized_at = finalizedAt;
    if (sentAt) update.invoice_sent_at = sentAt;
    if (paidAt) update.invoice_paid_at = paidAt;

    const { error } = await supabase
      .from('booking_payments')
      .update(update)
      .eq('booking_id', args.bookingId)
      .eq('attempt_no', args.attemptNo)
      .eq('stripe_invoice_id', args.invoice.id);

    if (error) {
      throw new Error(`Failed to update booking_payment row: ${error.message}`);
    }
  }

  private static async stampBookingFlowAndStatus(
    bookingId: string,
    flow: InvoiceFlow,
    status: 'AWAITING_INVOICE_PAYMENT' | 'AWAITING_INVOICE_CONFIRM',
  ): Promise<void> {
    // Stamp flow only if still legacy (idempotent, never downgrade).
    await supabase
      .from('bookings')
      .update({ payment_flow_version: flow, updated_at: this.nowIso() })
      .eq('id', bookingId)
      .eq('payment_flow_version', 'legacy');

    // Move status only from initial states (defensive — never overwrite
    // CONFIRMED / IN_PROGRESS / etc).
    await supabase
      .from('bookings')
      .update({ status, updated_at: this.nowIso() })
      .eq('id', bookingId)
      .in('status', ['NEW', 'PAYMENT_FAILED', 'PENDING_PAYMENT']);
  }

  private static async findLatestInvoiceRow(bookingId: string): Promise<ExistingInvoiceRow | null> {
    const { data } = await supabase
      .from('booking_payments')
      .select('id, attempt_no, stripe_invoice_id, stripe_invoice_number, hosted_invoice_url, status, stripe_invoice_status')
      .eq('booking_id', bookingId)
      .not('stripe_invoice_id', 'is', null)
      .order('attempt_no', { ascending: false })
      .limit(1)
      .maybeSingle();

    return (data as ExistingInvoiceRow | null) ?? null;
  }

  // ---- Stripe timestamp helpers --------------------------------------------

  private static stripeFinalizedAt(invoice: Stripe.Invoice): string | null {
    const ts = invoice.status_transitions?.finalized_at;
    return ts ? new Date(ts * 1000).toISOString() : null;
  }

  private static stripePaidAt(invoice: Stripe.Invoice): string | null {
    const ts = invoice.status_transitions?.paid_at;
    return ts ? new Date(ts * 1000).toISOString() : null;
  }

  private static nowIso(): string {
    return new Date().toISOString();
  }
}
